version: '3.8'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
      - "3000:3000"  # for Hello World app
    command: --storage-driver overlay2

  jenkins-blueocean:
    build: . # 현재 폴더의 Dockerfile을 사용하여 이미지를 빌드합니다.
    container_name: jenkins-blueocean
    restart: on-failure
    depends_on:
      - jenkins-docker
    networks:
      - jenkins
    environment:
      - DOCK-ER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge